name: Build linux wheels

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: [cp37-cp37m, cp38-cp38, cp39-cp39, cp310-cp310]
      fail-fast: false
    env:
      CONNECTOR_VERSION: "1.1.1"    
      py: /opt/python/${{ matrix.pyver }}/bin/python
      img: quay.io/pypa/manylinux2014_aarch64
    steps:
      - name: Cache Connector
        id: cache-connector
        uses: actions/cache@v1
        with:
          path: ~/mariadb-connector
          key: mariadb-connector-python-${{ env.CONNECTOR_VERSION }}-win

      - name: Download and Unzip Connector
        if: steps.cache-connector.outputs.cache-hit != 'true'
        shell: bash
        run: |
          curl -LO "https://downloads.mariadb.com/Connectors/python/connector-python-1.1.1/mariadb-connector-python-1.1.1.zip"
          unzip "mariadb-connector-python-${CONNECTOR_VERSION}-src.zip" -d ~/
          mv "c:/mariadb-connector-python-${CONNECTOR_VERSION}-src" ~/mariadb-connector-src
      - name: Build Connector
        if: steps.cache-connector.outputs.cache-hit != 'true'
        shell: bash
        working-directory: ~/mariadb-connector-src
        run: |
          mkdir build
          cd build
          cmake -A x64 .. -DCMAKE_BUILD_TYPE=Release -DCLIENT_PLUGIN_DIALOG=static -DCLIENT_PLUGIN_SHA256_PASSWORD=static -DCLIENT_PLUGIN_CACHING_SHA2_PASSWORD=static
          cmake --build . -j 8 --config Release
          cmake -DCMAKE_INSTALL_PREFIX=~/mariadb-connector -DCMAKE_INSTALL_COMPONENT=Development -DCMAKE_BUILD_TYPE=Release -P cmake_install.cmake    
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Build Wheel
        run: |
              docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
              ${{ env.img }} \
              bash -exc '${{ env.py }} -m venv .env && \
              source .env/bin/activate && \
              pip install -U setuptools wheel pip && \
              python setup.py bdist_wheel && \
              deactivate'
      - name: Upload Wheel
        uses: actions/upload-artifact@v2
        with:
          name: linux-wheels
          path: mysqlclient/dist/*.whl
